### ISSUE TITLE
испарвления

### ISSUE THREAD

**Issue by odinvolk** [Alexandr-logrus/majordomo-dimmer-device#1]
Александр  исправьте пожалуйста название файла dimmers_structure.php на SPhilipsDimmers_structure.php и строку в нём $this->device_types['dimmer'] = array( на $this->device_types['dimmerph'] = array( 
Потому что ломается структура нормальных димеров.

Спасибо

**Comment by Alexandr-logrus** [comment]
Спасибо за обратную связь!
Я с этим моментом видимо не понял, и у меня родные не используются, т.ч. и не заметил, поправил, проверил, вроде б нормально )
